name: shadertoy_client
version: 1.0.5
description: >-
  An http client implementation of the shadertoy API using
  Dio Http client. Supports the REST API (using an application key) 
  and the Site API (registered and anonymous users)
homepage: https://github.com/ivoleitao/shadertoy_client

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  meta: ^1.2.4
  enum_to_string: ^1.0.14
  path: ^1.7.0
  equatable: ^1.2.6
  pool: ^1.4.0
  retry: ^3.1.0
  dio: ^3.0.10
  cookie_jar: ^1.0.1
  dio_cookie_manager: ^1.0.0
  html: ^0.15.0
  intl: ^0.17.0
  envify: ^1.0.6
  shadertoy_api: ^1.0.13
  #shadertoy_api:
  #  path: ../shadertoy_api

dev_dependencies:
  pedantic: ^1.9.2
  build_runner: ^1.11.1
  envify_generator: ^1.0.6
  test: ^1.16.5
  test_coverage: ^0.5.0
  mockito: ^4.1.4

scripts: derry.yaml
