name: shadertoy_client
version: 1.0.4
description: >-
  An http client implementation of the shadertoy API using
  Dio Http client. Supports the REST API (using an application key) 
  and the Site API (registered and anonymous users)
homepage: https://github.com/ivoleitao/shadertoy_client

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  meta: ^1.2.4
  enum_to_string: ^1.0.14
  path: ^1.7.0
  equatable: ^1.2.5
  pool: ^1.4.0
  retry: ^3.0.1
  dio: ^3.0.10
  cookie_jar: ^1.0.1
  dio_cookie_manager: ^1.0.0
  html: ^0.14.0+4
  intl: ^0.16.1
  envify: ^1.0.6
  shadertoy_api: ^1.0.9
  # shadertoy_api:
  #  path: ../shadertoy_api

dev_dependencies:
  pedantic: ^1.9.2
  build_runner: ^1.10.11
  envify_generator: ^1.0.6
  test: ^1.15.7
  test_coverage: ^0.5.0
  mockito: ^4.1.3

scripts: derry.yaml
