name: build
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [stable]    

    steps:
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_API_KEY:
          envkey_USER:
          envkey_PASSWORD:
      - name: Install derry
        run: pub global activate derry
      - name: Build
        run: derry build
      - name: Verify
        run: derry verify
