name: build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install dependencies
        run: pub get
      - name: Copy environment file from template
        run: cp env.template .env
      - name: Generate sources
        run: pub run build_runner build
      - name: Run Formatter
        run: dartfmt -n --set-exit-if-changed .
      - name: Run Analyser
        run: dartanalyzer . --fatal-warnings
      - name: Run tests
        run: pub run test
