name: build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - name: Add pub to the path
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      - name: Install derry
        run: pub global activate derry
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare
        run: derry prepare
      - name: Build
        run: derry build
      - name: Verify
        run: derry verify
