name: publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - name: Install derry
        run: pub global activate derry
      - name: Add pub to the path
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare
        run: derry prepare
      - name: Build
        run: derry build
      - name: Verify
        run: derry verify
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
      - name: Add pub Credentials
        run: echo '${{ secrets.PUB_CREDENTIALS }}' > ~/.pub-cache/credentials.json
      - name: Publish
        run: derry publish
